### ISSUE TITLE
Sprite setFrame requires two arguments

### ISSUE THREAD

**Issue by ace-dent** [TinyCircuits/Thumby-Website#11]
The doc on `Sprite.setFrame(frame)` ([here](https://thumby.us/API/Sprites/)), suggests we just need 1 argument (frame number).
FIX: We need 2 arguments: object reference (sprite's name) and the frame number.

Bonus: Please add an example of using this frame function to animate a simple 2 frame image to 'Sprite example: Shapes & More!'. (Perhaps with FPS=1).

**Comment by Lennevia** [comment]
I had an example over here: https://thumby.us/Education/Moving-Walk/

But I added another one directly in the docs for getting and setting frames for clarity and better usability application: https://github.com/TinyCircuits/Thumby-Website/commit/7d1d2ce4e03f0e2a4d9663924d7bad476cecf8b4#diff-8341109e9c775f05fe13839a0b818cc4036cb58ffa59593c75189a1ac1db8866
