### ISSUE TITLE
Audio parameters not correct for GettingStarted

### ISSUE THREAD

**Issue by ace-dent** [TinyCircuits/Thumby-Website#12]
From:
https://thumby.us/API/Get-Started/

Audio section states that a third parameter `duty` is required. I think this is an error.
(Duty seems to be a fixed constant `0xFFFF//2`).

**Comment by Lennevia** [comment]
Good catch! Fixed. https://github.com/TinyCircuits/Thumby-Website/commit/884e738b001db03da715ef856fe93ecb5943198f
