### ISSUE TITLE
`sprite` coordinates - negatives are allowed?

### ISSUE THREAD

**Issue by ace-dent** [TinyCircuits/Thumby-Website#3]
The documentation for the [sprite](https://github.com/TinyCircuits/Thumby-Website/blob/main/docs/API/Sprites.md) and blitting, etc. API, suggest coordinates can only span `0` – `max`... but they seem to handle negative values ok. ...?

E.g. I want to scroll a larger image offscreen, to the top (`y=-40`) or left (`x=-72`).

Suggest docs are updated to give actual allowable range of values.

**Comment by ace-dent** [comment]
In addition, height and width are [specified](https://thumby.us/API/Blit-Draw/) in the docs as: `0`–`max-1`... 
I can understand setting to `0` to essential not blit the image, but surely you should be able to specify the full size? i.e. `0`–`max`.

**Comment by Lennevia** [comment]
Added a note to clarify: https://github.com/TinyCircuits/Thumby-Website/commit/175edb735e9e6f34eb5b96fb8e56e3c358f71c78
