### ISSUE TITLE
Add power saving example code

### ISSUE THREAD

**Issue by ace-dent** [TinyCircuits/Thumby-Website#4]
One use case is displaying fairly static screen images. 
It would be great to have example(s) showing how to maximize battery life. These might include best programming practices, warnings of potential issues (slow poling of user input, etc.), as well as any provisions that exist in the API. E.g.

 ```py
#...
from machine import freq
freq(1000000) # 1MHz minimum frequency?
#...

#...
thumby.setFPS(1) # minimise screen updates
#...
```

**Comment by ace-dent** [comment]
I've done some work on this. It seems that 24MHz is the lowest reliable frequency. Much lower and you start to hit display issues (offset images, etc.).
We can also use `machine.lightsleep(n)` – hopefully for some powersavings.

Example code is [here](https://gist.github.com/ace-dent/7bc73b4ad466331af0d1917834261a8a).

Update:
Just finished testing, static screen image, 93% lit pixels... ran for 4 hours and 8 mins !!!
Caveats: Brand new Thumby, fully charged. Running at ~23˚C. OLED may be degraded by long-term static images.

Things to try in the future:  
(0) Setup GPIO interrupts, so that lightsleep() can be used without the 2s alarm;  
(1) Adjust OLED clock multiplier, to see if lower CPU clocks can maintain a stable display;  
(2) Adjust OLED charge pump settings;  
(3) Other OLED CMD tweaks?;  
(4) Disable any unnecessary RP2040 peripherals/ features (audio amp, ADC, timers, etc.)

**Comment by Lennevia** [comment]
Added some of the examples with notes here: https://github.com/TinyCircuits/Thumby-Website/commit/9e08c168a243775b66c3c6b6710225cc23fbbdcd
