### ISSUE TITLE
Define colour values of `0` and `1`

### ISSUE THREAD

**Issue by ace-dent** [TinyCircuits/Thumby-Website#6]
Wherever the API docs mention a `color`, please explicitly state:
" `0` is black (unlit) and `1` is white (lit) "... even if it seems obvious.

e.g. as a newcomer, I wasn't sure what to set for text color based on the [doc](https://thumby.us/API/Text-and-Font/#printing-text).

For clarity, is it possible to add 'macro' values to the API, like `BLACK` and `WHITE`(see [Arduboy](https://github.com/MLXXXp/Arduboy2/blob/7dc88bed3031ab01d3227d065123740e4d938093/src/Arduboy2.h#L77-L79)) ...?

**Comment by Lennevia** [comment]
I see what you're saying. I'll start adding some language, but I'm not sure this discussion is over since there are also other colors when people are using grayscale hahah
Here's what I've done: https://github.com/TinyCircuits/Thumby-Website/commit/22428ab24f9d0cc47716a043dfcfaf6779cef530

**Comment by ace-dent** [comment]
From [Discord](https://discord.com/channels/898292107289190461/996871099499425873/1067857961340379176):
```
BLACK     = 0
WHITE     = 1
DARKGRAY  = 2
LIGHTGRAY = 3
```

**Comment by Lennevia** [comment]
I have some documentation up for grayscale and color values on the FAQ for now: https://thumby.us/FAQ/#grayscale-on-thumby

I'll keep colors in mind going forward when using integer values that refer to them, closing this!
