### ISSUE TITLE
Font sizes

### ISSUE THREAD

**Issue by ace-dent** [TinyCircuits/Thumby-Website#8]
Font details only 5x7 and 8x8 variations ([here](https://github.com/TinyCircuits/Thumby-Website/blob/9cce3ec194f743914e5eadb0f00a663b07ae7a01/docs/API/Text-and-Font.md#setting-font)).

Please mention the [added](https://github.com/TinyCircuits/TinyCircuits-Thumby-Code-Editor/commits/master/ThumbyGames/lib/font3x5.bin) 3x5 variation.

**Comment by Lennevia** [comment]
True! Updated the docs and animation: https://github.com/TinyCircuits/Thumby-Website/commit/5f5e12547fc33be2ecbf6d12989725bfb036ba6c
